# Colors (Dimidium)

[colors.bright]
black = '#565554'
blue = '#688dfd'
cyan = '#32e0fb'
green = '#37e57b'
magenta = '#ed6fe9'
red = '#ff643b'
white = '#dad6d5'
yellow = '#fccd1a'

[colors.cursor]
cursor = '#37e57b'
text = '#dad6d5'

[colors.normal]
black = '#000000'
blue = '#0575d8'
cyan = '#1db6bb'
green = '#60b442'
magenta = '#af5ed2'
red = '#cf494c'
white = '#bab7b6'
yellow = '#db9c11'

[colors.primary]
background = '#141414'
foreground = '#bab7b6'

[colors.selection]
background = '#8db8e5'
text = '#141414'
