# Dimidium
[colors]
foreground = "#bab7b6"
background = "#141414"
cursor_bg = "#37e57b"
cursor_border = "#37e57b"
cursor_fg = "#dad6d5"
selection_bg = "#8db8e5"
selection_fg = "#141414"

ansi = ["#000000","#cf494c","#60b442","#db9c11","#0575d8","#af5ed2","#1db6bb","#bab7b6"]
brights = ["#565554","#ff643b","#37e57b","#fccd1a","#688dfd","#ed6fe9","#32e0fb","#dad6d5"]
