[colors]
background = '#141414'
foreground = '#bab7b6'
selection-background = '#8db8e5'
selection-foreground = '#141414'
cursor = '#37e57b'
black = '#000000'
red = '#cf494c'
green = '#60b442'
yellow = '#db9c11'
blue = '#0575d8'
magenta = '#af5ed2'
cyan = '#1db6bb'
white = '#bab7b6'
light_black = '#817e7e'
light_red = '#ff643b'
light_green = '#37e57b'
light_yellow = '#fccd1a'
light_blue = '#688dfd'
light_magenta = '#ed6fe9'
light_cyan = '#32e0fb'
light_white = '#d3d8d9'
